name: publish gem
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: release ruby gem
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Checkout GitHub Actions Repo
      uses: actions/checkout@v2
      with:
        repository: leitfaden/github_actions
        ref: master
        token: ${{ secrets.PUBLISH_GEM_BY_ACTIONS }}
        path: .github/actions/
    - name: Bump version and push tag
      uses: ./.github/actions/github_tag_action
      id: bumVersion
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch
    - name: Build and publish gem
      uses: ./.github/actions/publish_gem
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        owner: leitfaden
        version: ${{ steps.bumVersion.outputs.new_tag}}
