# Copyright (c) 2023, all rights reserved.
#
# All the information provided by this platform is protected by international laws related  to
# industrial property, intellectual property, copyright and relative international laws.
# All intellectual or industrial property rights of the code, texts, trade mark, design,
# pictures and any other information belongs to the owner of this platform.
#
# Without the written permission of the owner, any replication, modification,
# transmission, publication is strictly forbidden.
#
# For more information read the license file including with this software.


# Specs for Lesli Module
# -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-
name: "Lesli build and publish gem"
on:
  push:
    branches: [ "production" ]

jobs:
  version:
    name: Build new engine version
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'release(gem):') && !contains(github.event.head_commit.message, 'assets(js):') && !contains(github.event.head_commit.message, 'ci(workflows):')"

    steps:

      # Send a message to slack announcing the workflow start
      - name: Notify slack github actions start
        uses: LesliTech/github-action-slack-job-status@v1
        with:
          channel: alerts
          job-status: INFO
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          msg: Generating gem for [${{ github.event.repository.name }}]


      # Clone the core repository
      - name: Checkout core
        uses: actions/checkout@v3
        with:
          repository: leitfaden/Lesli
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.PUBLISH_GEM_BY_ACTIONS }}


      # Clone the current repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          path: ./engines/${{ github.event.repository.name }}
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.PUBLISH_GEM_BY_ACTIONS }}


      # Clone our custom actions
      - name: Checkout github actions repo
        uses: actions/checkout@v3
        with:
          ref: master
          repository: leitfaden/github_actions
          token: ${{ secrets.PUBLISH_GEM_BY_ACTIONS }}
          path: ./tmp/.github/


      # Install node dependencies
      - name: NPM install
        run: npm install


      # Install node dependencies for vue2 apps
      - name: NPM install vue2
        run: npm install --prefix ./lib/vue2


      # Compile vue2 app
      - name: Compile Js vue2 for Production
        run: npm run webpack2:production


      # Compile vue3 app
      - name: Compile Js vue3 for Production
        run: npm run webpack3:production


      # Commit the javascript apps so the gem includes the compiled version
      - name: Commit compiled javascript app
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: engines/${{ github.event.repository.name }}
          commit_message: "assets(js): Compile Js to Production"
          branch: production
        env:
          TOKEN: ${{ secrets.PUBLISH_GEM_BY_ACTIONS }}


      # Build a new version for the core
      - name: Bump version and push tag
        uses: ./tmp/.github/actions/github-action-rails-new-version
        id: bumpVersion
        env:
          SOURCE: engines/${{ github.event.repository.name }}
          RELEASE_BRANCHES: production
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      # Build the gem and publish in github packages
      - name: Build and publish gem
        uses: ./tmp/.github/actions/github-action-publish-gem-to-github
        with:
          owner: leitfaden
          token: ${{ secrets.PUBLISH_GEM_BY_ACTIONS }}
          version: ${{ steps.bumpVersion.outputs.new_tag}}
          working-directory: engines/${{ github.event.repository.name }}


      # Synchronize the production & master branches so we keep the version files
      - name: Sync master branch with production branch
        uses: ./tmp/.github/actions/github-action-sync-branches
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_branch: production
          to_branch: master
          source: engines/${{ github.event.repository.name }}


      # The newly created tag is deleted if a step fails or the workflow is cancelled.
      - name: Delete Tag
        if: "cancelled() || failure()"
        run: git push --delete origin ${{ steps.bumpVersion.outputs.new_tag }}


      # Send a message to slack with the status of the workflow
      - name: Notify by slack
        if: always()
        uses: LesliTech/github-action-slack-job-status@v1
        with:
          job-status: ${{ job.status }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: alerts

