name: Build and Publish GEM
on:
  push:
    branches:
      - production
jobs:
  build_publish:
    name: Build and publish
    runs-on: lomax
    if: "!contains(github.event.head_commit.message, 'release(gem):')"
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.PUBLISH_GEM_BY_ACTIONS }}
    - run: |
        git config user.name 'github-actions'
        git config user.email 'github-actions@github.com'
    - name: Checkout github actions repo
      uses: actions/checkout@v2
      with:
        repository: leitfaden/github_actions
        ref: production
        token: ${{ secrets.PUBLISH_GEM_BY_ACTIONS }}
        path: ./.github/
    - name: Notify slack github actions start 
      uses: ./.github/actions/slack_job_status
      with:
        job-status: INFO
        slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
        channel: alerts
        msg: Generating gem for [${{ github.event.repository.name }}]
    - name: New tag version
      uses: ./.github/actions/git_tag_new_version
      id: bumVersion
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch
    - name: Checkout core repo
      uses: actions/checkout@v2
      with:
        repository: leitfaden/Lesli
        ref: production
        token: ${{ secrets.PUBLISH_GEM_BY_ACTIONS }}
        path: ./Lesli
    - name: "Checkout ${{ github.event.repository.name }} repo"
      uses: actions/checkout@v2
      with:
        path: ./Lesli/engines/${{ github.event.repository.name }}/
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ./Lesli/lib/vue2/node_modules
        key: ${{ runner.os }}-${{ github.event.repository.name }}-node-${{ hashFiles('./Lesli/package.json') }}
        restore-keys: |
          ${{ runner.os }}-${{ github.event.repository.name }}-node-
    - name: NPM install vue2
      run: |
        cd ./Lesli
        npm install --prefix ./lib/vue2
        cd ..
    - name: Compile Js vue2 for Production
      run: |
        cd ./Lesli/
        npm run webpack:production
        cd ..
    - name: NPM install vue3
      run: |
        cd ./Lesli
        npm install 
        cd ..
    - name: Compile Js vue3 for Production
      run: |
        cd ./Lesli/
        npm run webpack3:production
        cd ..
    - name: Commit compiled javascript app
      run: |
        if [ -d "./Lesli/engines/${{ github.event.repository.name }}/app/assets/" ]
        then
          echo "Copying compiled assets"
          cp --verbose --archive --recursive --force ./Lesli/engines/${{ github.event.repository.name }}/app/assets/* ./app/assets/
        fi
        rm -r  ./Lesli/
    - name: Build and publish gem
      uses: ./.github/actions/rails_gem_build_and_publish
      with:
        token: ${{ secrets.PUBLISH_GEM_BY_ACTIONS }}
        owner: leitfaden
        version: ${{ steps.bumVersion.outputs.new_tag}}
    - name: Delete tag
      if: "cancelled() || failure()"
      run: |
        # The newly created tag is deleted if a step fails or the workflow is cancelled.
        git push --delete origin ${{ steps.bumVersion.outputs.new_tag}}
    - name: Sync master branch with production branch
      if: always()
      uses: ./.github/actions/git_branch_sync_branches
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        from_branch: production
        to_branch: master
    - name: Notify by slack
      if: always()
      uses: ./.github/actions/slack_job_status
      with:
        job-status: ${{ job.status }}
        slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
        channel: alerts
